Checkout sample app with script step

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -80,16 +80,24 @@ workflows:
         inputs:
         - path: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
         - is_create_path: true
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: $COMMIT
-        - tag: ""
-        - branch: ""
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+              echo "error: there is no SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+
     - certificate-and-profile-installer:
     - path::./:
         inputs:
